name: "ğŸ§ª Â» test"
on: 
  workflow_call:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  lint:
    name: "ğŸ§¹ Â» lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    
    steps:
      - name: ğŸ“ Â» checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ Â» setup python, poetry and task
        uses: ./.github/workflows/composites/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ“¦ Â» install ruff globally
        run: pip install ruff      

      - name: ğŸ§¹ Â» lint
        run: task lint:check

  test:
    name: "ğŸ§ª Â» tests"
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    
    steps:
      - name: ğŸ“ Â» checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ Â» setup python, poetry and task
        uses: ./.github/workflows/composites/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ§ª Â» run tests
        run: task test:${{ matrix.python-version }}

      # if python 3.11, upload coverage to codecov
      - name: â˜‚ï¸ Â» upload coverage to codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
